baseURL = "https://example.org/"
title = "My Custom Hugo Site"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
theme = "MyCustomTheme"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
mainSections = ["portfolio", "docs"]

[params.homeInfo]
title = "Welcome to My Custom Hugo Site"
description = "A minimalist black, white, and gray themed site showcasing my portfolio and technical documentation."

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/"

[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://linkedin.com/"

["params.homeInfo"]
description = "^ w ^"
title = "hello"
