name = "MyCustomTheme"
license = "MIT"
licenselink = ""
description = "A custom theme combining elements from PaperMod, Mainroad, and Hugo-Book"
homepage = ""
tags = ["responsive", "minimal", "clean", "blog", "portfolio", "documentation"]
features = ["responsive", "minimalist", "sidebar", "search", "categories", "tags"]
min_version = "0.60.0"

[author]
  name = "Custom Theme Creator"
  homepage = ""
