backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1

# 媒体文件存储位置
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# 内容集合
collections:
  - name: "site_settings"
    label: "网站设置与主页"
    files:
      - file: "hugo.toml"
        label: "基本设置"
        name: "general"
        fields:
          - {label: "网站标题", name: "title", widget: "string"}
          - {label: "语言代码", name: "languageCode", widget: "string"}
          - {label: "默认内容语言", name: "defaultContentLanguage", widget: "string"}
          - label: "主页信息"
            name: "params.homeInfo"
            widget: "object"
            fields:
              - {label: "欢迎标题", name: "title", widget: "string"}
              - {label: "网站描述", name: "description", widget: "text"}
          - label: "社交图标"
            name: "params.socialIcons"
            widget: "list"
            fields:
              - {label: "名称", name: "name", widget: "string"}
              - {label: "链接", name: "url", widget: "string"}
      - file: "content/_index.md"
        label: "主页内容"
        name: "home"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "描述", name: "description", widget: "text"}
          - label: "社交图标"
            name: "socialIcons"
            widget: "list"
            fields:
              - {label: "名称", name: "name", widget: "string"}
              - {label: "链接", name: "url", widget: "string"}
          - {label: "页面内容", name: "body", widget: "markdown"}

  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    nested:
      depth: 10
      summary: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false, hint: "将此文章标记为精选，显示在首页"}
      - {label: "Weight", name: "weight", widget: "number", required: false, hint: "控制在同级内容中的顺序"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "docs"
    label: "Documentation"
    folder: "content/docs"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    nested:
      depth: 10
      summary: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false, hint: "将此文档标记为精选，显示在首页"}
      - {label: "Weight", name: "weight", widget: "number", required: false, hint: "控制在同级内容中的顺序"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
